/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package modal.views;

import domain.Passagem;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import modal.dao.PassagemDAO;

/**
 *
 * @author gllbo
 */
public class Faturamento extends javax.swing.JInternalFrame {

    /**
     * Creates new form Faturamento
     */
    public Faturamento() {
        initComponents();
    }
    
    public void ListagemPassagem() throws SQLException {
        try {
            
            Double totfaturamento = 0.0;
            
            PassagemDAO passagemdao = new PassagemDAO();
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");

            String dtcInicioText = tfdtcinicio.getText();
            String dtcFinalText = tfdtcfinal.getText();

            Date dtcInicio = dateFormat.parse(dtcInicioText);
            Date dtcFinal = dateFormat.parse(dtcFinalText);

            List<Passagem> listapassagems = passagemdao.faturamento(dtcInicio, dtcFinal);
            
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("COD Passagem");
            model.addColumn("Cidade Origem");
            model.addColumn("Cidade Destino");
            model.addColumn("Placa Veiculo");
            model.addColumn("Poltrona");
            model.addColumn("Data Saida");
            model.addColumn("Hora Saida");
            model.addColumn("Valor Passagem");

           for (Passagem passagem : listapassagems) {
                model.addRow(new Object[]{
                    passagem.getIdpassagem(),
                    passagem.getCidadeorigem() != null ? passagem.getCidadeorigem().getNomeCidade() : "",
                    passagem.getCidadedestino() != null ? passagem.getCidadedestino().getNomeCidade() : "",
                    passagem.getVeiculo() != null ? passagem.getVeiculo().getPlaca() : "",
                    passagem.getPoltrona(),
                    passagem.getDatasaida(),
                    passagem.getHorasaida(),
                    passagem.getValorpassagem(),
                    totfaturamento = totfaturamento + passagem.getValorpassagem()
                });
            }

            lbtotfaturamento.setText(totfaturamento.toString());
            tlistacidade.setModel(model);
        } catch (ParseException e) {
            e.printStackTrace();
        } catch (SQLException e) {
            e.printStackTrace();
        } catch (Exception ex) {
            Logger.getLogger(Faturamento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tlistacidade = new javax.swing.JTable();
        btnvoltarcidade = new javax.swing.JButton();
        tfdtcinicio = new javax.swing.JFormattedTextField();
        tfdtcfinal = new javax.swing.JFormattedTextField();
        btnfiltrar = new javax.swing.JButton();
        lbtotfaturamento = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        tlistacidade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tlistacidade);

        btnvoltarcidade.setText("Voltar");
        btnvoltarcidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvoltarcidadeActionPerformed(evt);
            }
        });

        tfdtcinicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        tfdtcfinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        btnfiltrar.setText("Filtrar");
        btnfiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfiltrarActionPerformed(evt);
            }
        });

        jLabel1.setText("Total Faturamento:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnvoltarcidade))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(tfdtcinicio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tfdtcfinal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnfiltrar)
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbtotfaturamento)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(11, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfdtcinicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfdtcfinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnfiltrar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbtotfaturamento)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(btnvoltarcidade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnvoltarcidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvoltarcidadeActionPerformed
        // TODO add your handling code here:
        Menu menu = (Menu) SwingUtilities.getWindowAncestor(this);
        menu.btncidade.setVisible(true);
        menu.btnveiculo.setVisible(true);
        menu.btnusuario.setVisible(true);
        menu.btnpassagem.setVisible(true);
        menu.btnfaturamento.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnvoltarcidadeActionPerformed

    private void btnfiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfiltrarActionPerformed
        try {
            // TODO add your handling code here:
            ListagemPassagem();
        } catch (SQLException ex) {
            Logger.getLogger(Faturamento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnfiltrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnfiltrar;
    private javax.swing.JButton btnvoltarcidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbtotfaturamento;
    private javax.swing.JFormattedTextField tfdtcfinal;
    private javax.swing.JFormattedTextField tfdtcinicio;
    private javax.swing.JTable tlistacidade;
    // End of variables declaration//GEN-END:variables
}
