/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package modal.views;

import domain.Veiculo;
import java.sql.SQLException;
import java.util.List;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import modal.dao.VeiculoDAO;

/**
 *
 * @author gllbo
 */
public class ListaVeiculo extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListaVeiculo
     */
    public ListaVeiculo() {
        initComponents();
        
        try {
            ListagemVeiculo();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
    public void ListagemVeiculo() throws SQLException {
        VeiculoDAO veiculodao = new VeiculoDAO();
        List<Veiculo> listaveiculos = veiculodao.listarTodosVeiculos();

        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Placa");
        model.addColumn("Motorista");
        model.addColumn("Modelo");
        model.addColumn("Ano do Modelo");
        model.addColumn("Quantidade de Poltronas");
        model.addColumn("Número");

        for (Veiculo veiculo : listaveiculos) {
            model.addRow(new Object[]{
                veiculo.getPlaca(),
                veiculo.getMotorista(),
                veiculo.getModelo(),
                veiculo.getAnomodelo(),
                veiculo.getQtdpoltronas(),
                veiculo.getNumero()
            });
        }

        tlistaveiculo.setModel(model);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tlistaveiculo = new javax.swing.JTable();
        btnvoltarveiculo = new javax.swing.JButton();

        tlistaveiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tlistaveiculo);

        btnvoltarveiculo.setText("Voltar");
        btnvoltarveiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvoltarveiculoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnvoltarveiculo))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(btnvoltarveiculo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnvoltarveiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvoltarveiculoActionPerformed
        // TODO add your handling code here:
        VeiculoViews veiculoviews = new VeiculoViews();

        Menu menu = (Menu) SwingUtilities.getWindowAncestor(this);
        menu.getDpmenu().add(veiculoviews);

        veiculoviews.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnvoltarveiculoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnvoltarveiculo;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tlistaveiculo;
    // End of variables declaration//GEN-END:variables
}
