/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package modal.views;

import conectabd.Conexao;
import domain.Cidade;
import domain.Passagem;
import domain.Veiculo;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import modal.dao.CidadeDAO;
import modal.dao.PassagemDAO;
import modal.dao.VeiculoDAO;

/**
 *
 * @author gllbo
 */
public class PassagemViews extends javax.swing.JInternalFrame {

    /**
     * Creates new form PassagemViews
     */
    Vector<Integer> id = new Vector<Integer>();
    Vector<Integer> id2 = new Vector<Integer>();
    
   private void popularComboCidadesOrigem() {
        try {
            CidadeDAO cidadedao = new CidadeDAO();
            ResultSet cidades = cidadedao.listarCidades();
            
            VeiculoDAO veiculodao = new VeiculoDAO();
            ResultSet veiculos = veiculodao.listarVeiculos();

            cbidecidadeorigem.removeAllItems();
            cbidecidadedestino.removeAllItems();
            cbdesplaca.removeAllItems();

            while (cidades.next()) {
                id.addElement(cidades.getInt(1));
                cbidecidadeorigem.addItem(cidades.getString(2));
            }

            cidades.close();
            cidades = cidadedao.listarCidades();

            while (cidades.next()) {
                id2.addElement(cidades.getInt(1));
                cbidecidadedestino.addItem(cidades.getString(2));
            }

            cidades.close();
            veiculos = veiculodao.listarVeiculos();

            while (veiculos.next()) {
                cbdesplaca.addItem(veiculos.getString(1));
            }

            cidades.close();

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    
    public PassagemViews() {
        initComponents();
        
        popularComboCidadesOrigem();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfpesqpassagem = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnsalvarcidade = new javax.swing.JButton();
        btnexcluircidade = new javax.swing.JButton();
        btnlistacidade = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnpesqpassagem = new javax.swing.JButton();
        tfidepassagem = new javax.swing.JTextField();
        btnlimparcidade = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbidecidadeorigem = new javax.swing.JComboBox<>();
        cbidecidadedestino = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        tfnropoltrona = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfdtcsaida = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        tfhorasaida = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        tfvalpassagem = new javax.swing.JFormattedTextField();
        cbdesplaca = new javax.swing.JComboBox<>();
        btnvoltarcidade = new javax.swing.JButton();

        jLabel1.setText("ID Passagem");

        jLabel3.setText("Nome da Cidade Origem");
        jLabel3.setToolTipText("");

        btnsalvarcidade.setText("Salvar");
        btnsalvarcidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvarcidadeActionPerformed(evt);
            }
        });

        btnexcluircidade.setText("Excluir");
        btnexcluircidade.setEnabled(false);
        btnexcluircidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexcluircidadeActionPerformed(evt);
            }
        });

        btnlistacidade.setText("Lista");
        btnlistacidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlistacidadeActionPerformed(evt);
            }
        });

        jLabel7.setText("Pesquisar por ID");

        btnpesqpassagem.setText("Buscar");
        btnpesqpassagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpesqpassagemActionPerformed(evt);
            }
        });

        tfidepassagem.setEnabled(false);

        btnlimparcidade.setText("Limpar");
        btnlimparcidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimparcidadeActionPerformed(evt);
            }
        });

        jLabel4.setText("Nome da Cidade Destino");
        jLabel4.setToolTipText("");

        jLabel2.setText("Placa do Veiculo");

        cbidecidadeorigem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbidecidadedestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Nº Poltronas");

        jLabel6.setText("Data Saida");

        tfdtcsaida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        jLabel8.setText("Hora Saida");

        tfhorasaida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        tfhorasaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfhorasaidaActionPerformed(evt);
            }
        });

        jLabel9.setText("Valor da Passagem");

        tfvalpassagem.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        tfvalpassagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfvalpassagemActionPerformed(evt);
            }
        });

        cbdesplaca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnvoltarcidade.setText("Voltar");
        btnvoltarcidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvoltarcidadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(325, Short.MAX_VALUE)
                .addComponent(btnlistacidade)
                .addGap(18, 18, 18)
                .addComponent(btnlimparcidade)
                .addGap(18, 18, 18)
                .addComponent(btnexcluircidade)
                .addGap(18, 18, 18)
                .addComponent(btnsalvarcidade)
                .addGap(42, 42, 42))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfpesqpassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnpesqpassagem))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(81, 81, 81))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(cbdesplaca, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(tfnropoltrona, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(tfdtcsaida, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(tfhorasaida, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfvalpassagem)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(tfidepassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel3))
                                    .addComponent(cbidecidadeorigem, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel4))
                                    .addComponent(cbidecidadedestino, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnvoltarcidade)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnvoltarcidade)
                .addGap(19, 19, 19)
                .addComponent(jLabel7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnpesqpassagem)
                    .addComponent(tfpesqpassagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbidecidadedestino, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(28, 28, 28)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbidecidadeorigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfidepassagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(28, 28, 28))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(tfnropoltrona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbdesplaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfhorasaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfvalpassagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfdtcsaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsalvarcidade)
                    .addComponent(btnexcluircidade)
                    .addComponent(btnlistacidade)
                    .addComponent(btnlimparcidade))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsalvarcidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvarcidadeActionPerformed
        // TODO add your handling code here:
        try {
            if (tfnropoltrona.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Todos os campos obrigatórios devem ser preenchidos", "Erro", JOptionPane.ERROR_MESSAGE);
            } else {
                Passagem passagem = new Passagem();
                Connection suaConexao = Conexao.getConnection();
                PassagemDAO passagemdao = new PassagemDAO(suaConexao);
                
                
                CidadeDAO cidadedao = new CidadeDAO();
                VeiculoDAO veiculodao = new VeiculoDAO();
                
                String placaVeiculo = (String) cbdesplaca.getSelectedItem();
                
                int idCidadeOrigem = id.get(cbidecidadeorigem.getSelectedIndex());
                int idCidadeDestino = id2.get(cbidecidadedestino.getSelectedIndex());

                Cidade cidadeOrigem = cidadedao.obterCidadePorId(idCidadeOrigem);
                Cidade cidadeDestino = cidadedao.obterCidadePorId(idCidadeDestino);
                Veiculo veiculo = veiculodao.consultarVeiculoPorPlaca(placaVeiculo);

                passagem.setCidadeorigem(cidadeOrigem);
                passagem.setCidadedestino(cidadeDestino);
                passagem.setVeiculo(veiculo);
                Integer totalPoltronasVeiculo = veiculo.getQtdpoltronas();

                Integer poltrona = Integer.valueOf(tfnropoltrona.getText());
                if (poltrona <= totalPoltronasVeiculo) {
                    passagem.setPoltrona(poltrona);
                }else {
                    JOptionPane.showMessageDialog(null, "Número de poltrona inválido. O veículo possui apenas " + totalPoltronasVeiculo + " poltronas.", "Erro", JOptionPane.ERROR_MESSAGE);
                }
                String dataSaidaText = tfdtcsaida.getText().trim();
                SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
                Date dataSaida = dateFormat.parse(dataSaidaText);
                passagem.setDatasaida(dataSaida);
                passagem.setHorasaida(tfhorasaida.getText());
                
                String valPassagemText = tfvalpassagem.getText().trim();
                valPassagemText = valPassagemText.replace(",", ".");
                try {
                    if (!valPassagemText.isEmpty()) {
                        passagem.setValorpassagem(Double.valueOf(valPassagemText));
                    } else {
                        JOptionPane.showMessageDialog(null, "Please enter a valid value for the passagem", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "Invalid format for passagem value", "Error", JOptionPane.ERROR_MESSAGE);
                }
                
                boolean seatAlreadySold = passagemdao.verificarPoltronaVendida(passagem);

                if (seatAlreadySold) {
                    JOptionPane.showMessageDialog(null, "Poltrona já vendida. Escolha outra poltrona.", "Aviso", JOptionPane.WARNING_MESSAGE);
                } else {
                    passagemdao.cadastrarPassagem(passagem);

                    tfidepassagem.setText("");
                    tfvalpassagem.setText("");
                    tfpesqpassagem.setText("");
                    tfnropoltrona.setText("");
                    tfhorasaida.setText("");
                    tfdtcsaida.setText("");  
                }    
            }
        } catch (SQLException e) {
        } catch (Exception ex) {
            Logger.getLogger(PassagemViews.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnsalvarcidadeActionPerformed

    private void btnexcluircidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexcluircidadeActionPerformed
        // TODO add your handling code here:
        try {
            if (tfpesqpassagem.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "O campo de pesquisa deve ser preenchido", "Erro", JOptionPane.ERROR_MESSAGE);
            } else {
                int opcao = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir o veículo?", "Confirmação", JOptionPane.YES_NO_OPTION);

                Passagem passagem = new Passagem();
                PassagemDAO passagemdao = new PassagemDAO();
                if (opcao == JOptionPane.YES_OPTION) {
                    passagem = passagemdao.obterPassagemPorId(Integer.valueOf(tfpesqpassagem.getText()));

                    passagemdao.excluirPassagem(passagem.getIdpassagem());

                    btnexcluircidade.setEnabled(false);
                    btnsalvarcidade.setEnabled(true);
                    
                    tfidepassagem.setText("");
                    tfvalpassagem.setText("");
                    tfpesqpassagem.setText("");
                    tfnropoltrona.setText("");
                    tfhorasaida.setText("");
                    tfdtcsaida.setText("");
                }
            }

        } catch (SQLException e) {
        }
    }//GEN-LAST:event_btnexcluircidadeActionPerformed

    private void btnlistacidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlistacidadeActionPerformed
        // TODO add your handling code here:
        ListaPassagem listaPassagemFrame = new ListaPassagem();

        Menu menu = (Menu) SwingUtilities.getWindowAncestor(this);
        menu.getDpmenu().add(listaPassagemFrame);

        listaPassagemFrame.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnlistacidadeActionPerformed

    private void btnpesqpassagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpesqpassagemActionPerformed
        // TODO add your handling code here:
        try {
            if (tfpesqpassagem.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "O campo de pesquisa deve ser preenchido", "Erro", JOptionPane.ERROR_MESSAGE);
            } else {
                PassagemDAO passagemdao = new PassagemDAO();
                
                int idPassagem = Integer.valueOf(tfpesqpassagem.getText());
                Passagem passagem = passagemdao.obterPassagemPorId(idPassagem);

                tfidepassagem.setText(passagem.getIdpassagem().toString());
                tfvalpassagem.setText(passagem.getValorpassagem().toString());
                tfnropoltrona.setText(passagem.getPoltrona().toString());
                tfhorasaida.setText(passagem.getHorasaida());
                
                SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
                tfdtcsaida.setText(dateFormat.format(passagem.getDatasaida()));

                btnsalvarcidade.setEnabled(false);
                btnexcluircidade.setEnabled(true);
            }

        } catch (SQLException e) {
            tfpesqpassagem.setText("");
        }
    }//GEN-LAST:event_btnpesqpassagemActionPerformed

    private void btnlimparcidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimparcidadeActionPerformed
        // TODO add your handling code here:
        tfidepassagem.setText("");
        tfpesqpassagem.setText("");
        tfvalpassagem.setText("");
        tfnropoltrona.setText("");
        tfhorasaida.setText("");
        tfdtcsaida.setText("");
        btnsalvarcidade.setEnabled(true);
        btnexcluircidade.setEnabled(false);
    }//GEN-LAST:event_btnlimparcidadeActionPerformed

    private void tfhorasaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfhorasaidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfhorasaidaActionPerformed

    private void tfvalpassagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfvalpassagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfvalpassagemActionPerformed

    private void btnvoltarcidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvoltarcidadeActionPerformed
        // TODO add your handling code here:
        Menu menu = (Menu) SwingUtilities.getWindowAncestor(this);
        menu.btncidade.setVisible(true);
        menu.btnveiculo.setVisible(true);
        menu.btnusuario.setVisible(true);
        menu.btnpassagem.setVisible(true);
        menu.btnfaturamento.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnvoltarcidadeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnexcluircidade;
    private javax.swing.JButton btnlimparcidade;
    private javax.swing.JButton btnlistacidade;
    private javax.swing.JButton btnpesqpassagem;
    private javax.swing.JButton btnsalvarcidade;
    private javax.swing.JButton btnvoltarcidade;
    private javax.swing.JComboBox<String> cbdesplaca;
    private javax.swing.JComboBox<String> cbidecidadedestino;
    private javax.swing.JComboBox<String> cbidecidadeorigem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JFormattedTextField tfdtcsaida;
    private javax.swing.JFormattedTextField tfhorasaida;
    private javax.swing.JTextField tfidepassagem;
    private javax.swing.JTextField tfnropoltrona;
    private javax.swing.JTextField tfpesqpassagem;
    private javax.swing.JFormattedTextField tfvalpassagem;
    // End of variables declaration//GEN-END:variables
}
